<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>

      <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

      <title>${titulo}</title>

      <link href="favicon.ico" rel="shortcut icon" type="image/x-icon" />

      <style type="text/css" rel="stylesheet" media="all">

        @media only screen and (max-width: 600px) {
          .email-body_inner,
          .email-footer {
            width: 100% !important;
          }
        }

        @media only screen and (max-width: 500px) {
          .button {
            width: 100% !important;
          }

        }

      </style>

    </head>

    <body style="width: 100% !important; height: 100%; margin: 0; line-height: 1.4; background-color: #F2F4F6; color: #74787E; -webkit-text-size-adjust: none;">

    </body>

</html>