export enum Funcionalidade {
    TDS = 'Todos',
    D = 'Departamento Regional',
    E = 'Empresa',
    PC = 'Parceiro Credenciado',
    PQS = 'Pesquisa SESI',
    PS = 'Produtos e Servicos',
    P = 'Profissional',
    Q = 'Questionário Trabalhador',
    RC = 'Rede Credenciada',
    RES = 'Registro de Saúde',
    S = 'Sindicato',
    T = 'Trabalhador',
    C = 'Unidade SESI',
    U = 'Usuários',
}