export enum PerfilEnum {
    ADM = 'ADM',
    ATD = 'ATD',
    TRA = 'TRA',
    DIDN = 'DIDN',
    DIDR = 'DIDR',
    GDNA = 'GDNA',
    GDNP = 'GDNP',
    GDRA = 'GDRA',
    GDRP = 'GDRP',
    GEEM = 'GEEM',
    GEPC = 'GEPC',
    GERC = 'GERC',
    GESI = 'GESI',
    SUPS = 'SUPS',
    SUPG = 'SUPG',
}
